import type { Property } from './types';

export const initialProperties: Property[] = [
  {
    id: 1,
    type: 'House',
    price: 850000,
    address: {
      street: '123 Maple St',
      city: 'Los Angeles',
      state: 'CA',
      zip: '90001',
    },
    bedrooms: 4,
    bathrooms: 3,
    area_sqft: 2500,
    imageUrl: 'https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    description: 'A beautiful modern house in a quiet neighborhood, perfect for families.',
    dateListed: '2024-07-20',
    isFavorited: false,
  },
  {
    id: 2,
    type: 'Apartment',
    price: 450000,
    address: {
      street: '456 Oak Ave',
      city: 'San Francisco',
      state: 'CA',
      zip: '94102',
    },
    bedrooms: 2,
    bathrooms: 2,
    area_sqft: 1200,
    imageUrl: 'https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    description: 'Chic downtown apartment with stunning city views and modern amenities.',
    dateListed: '2024-07-18',
    isFavorited: false,
  },
  {
    id: 3,
    type: 'Condo',
    price: 620000,
    address: {
      street: '789 Pine Ln',
      city: 'San Diego',
      state: 'CA',
      zip: '92101',
    },
    bedrooms: 3,
    bathrooms: 2,
    area_sqft: 1800,
    imageUrl: 'https://images.pexels.com/photos/1642125/pexels-photo-1642125.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    description: 'Luxurious condo with access to a pool, gym, and community center.',
    dateListed: '2024-07-22',
    isFavorited: false,
  },
  {
    id: 4,
    type: 'House',
    price: 1200000,
    address: {
      street: '101 Elm Ct',
      city: 'Beverly Hills',
      state: 'CA',
      zip: '90210',
    },
    bedrooms: 5,
    bathrooms: 5,
    area_sqft: 4500,
    imageUrl: 'https://images.pexels.com/photos/259588/pexels-photo-259588.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    description: 'Sprawling estate with a large backyard and private swimming pool.',
    dateListed: '2024-06-30',
    isFavorited: false,
  },
  {
    id: 5,
    type: 'Apartment',
    price: 380000,
    address: {
      street: '212 Birch Rd',
      city: 'Los Angeles',
      state: 'CA',
      zip: '90012',
    },
    bedrooms: 1,
    bathrooms: 1,
    area_sqft: 800,
    imageUrl: 'https://images.pexels.com/photos/2121121/pexels-photo-2121121.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    description: 'Cozy and affordable apartment, ideal for students or young professionals.',
    dateListed: '2024-07-15',
    isFavorited: false,
  },
  {
    id: 6,
    type: 'Plot',
    price: 250000,
    address: {
      street: 'Land on Hillside Dr',
      city: 'Malibu',
      state: 'CA',
      zip: '90265',
    },
    bedrooms: 0,
    bathrooms: 0,
    area_sqft: 21780,
    imageUrl: 'https://images.pexels.com/photos/1115816/pexels-photo-1115816.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    description: 'A prime plot of land with ocean views, ready for you to build your dream home.',
    dateListed: '2024-07-01',
    isFavorited: false,
  },
  {
    id: 7,
    type: 'House',
    price: 975000,
    address: {
      street: '777 Sunset Blvd',
      city: 'Los Angeles',
      state: 'CA',
      zip: '90046',
    },
    bedrooms: 4,
    bathrooms: 4,
    area_sqft: 3200,
    imageUrl: 'https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    description: 'Stunning contemporary home with high ceilings and an open floor plan.',
    dateListed: '2024-07-21',
    isFavorited: false,
  },
  {
    id: 8,
    type: 'Condo',
    price: 550000,
    address: {
      street: '333 Bay St',
      city: 'San Francisco',
      state: 'CA',
      zip: '94133',
    },
    bedrooms: 2,
    bathrooms: 2,
    area_sqft: 1400,
    imageUrl: 'https://images.pexels.com/photos/323775/pexels-photo-323775.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    description: 'Modern condo near the waterfront with easy access to shops and restaurants.',
    dateListed: '2024-07-19',
    isFavorited: false,
  }
];